[package]
name = "lxwengctl"
description = "CLI to interact with the daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints.clippy]
pedantic = "warn"

[dependencies]
clap.workspace = true
display-info = "0.5.4"
